name: Auto Approve and Merge

on:
  pull_request:
    types: [opened, reopened, synchronized]

jobs:
  automation:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      # Step 2.1: Automatically approve the Pull Request
      - name: Auto Approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          # Use a PAT instead of GITHUB_TOKEN to bypass branch protection rules that don't allow PR authors to approve
          github-token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

      # Step 2.2: Set the PR to automatically merge once status checks pass
      - name: Enable GitHub Auto-Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
